pipeline {
     agent any
     stages {
        stage('maven clean compile') {
             steps {
                 sh '''cd Backend
                 mvn clean compile '''
             }
        }

         stage('Mockito test'){
                     steps{
                        sh """mvn test """
                     }
                }
        stage('maventest Sonarqube'){
             steps{
                sh """mvn sonar:sonar -Dsonar.login=admin -Dsonar.password=sonar """
             }
        }
        stage('maven Package'){
             steps{
                 sh """mvn package -DskipTests=true """
             }
        }
        stage('Install .m2 '){
             steps{
                 sh """mvn install  """
             }
        }
        stage('maven Deploy Nexus'){
             steps{
                 sh """mvn deploy  """
             }
        }
        stage('Docker image'){
             steps{
                 sh ''' docker login -u fediijat -p kopp92i11
                  docker build -t fediijat/valoparamadmin --build-arg JAR_URL=http://192.168.33.10:8081/repository/maven-releases/tn/esprit/spring/5SAE4-G2-gestion-station-ski/1.0/5SAE4-G2-gestion-station-ski-1.0.jar . '''
             }
        }
        stage('Docker Push'){
             steps{
                 sh """ docker push  fediijat/valoparamadmin """
             }
        }
     }
}
