apiVersion: apps/v1 # Where in the API it resides
kind: Deployment # The kind of workload we're creating
metadata:
  name: valoparamapi
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valoparamapi
  template:
    metadata:
      labels:
        app: valoparamapi
    spec:
      containers:
        - name: valoparamapi
          image: fediijat/valoparamadminbackend
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
