apiVersion: v1
kind: Service
metadata:
  name: valoparamapi-service
  namespace: dev
spec:
  selector:
    app: valoparamapi
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
