pipeline {
    agent any
    tools {
        nodejs 'nodenode'
    }
    stages {
        stage('Install Packages') {
            steps {
                dir('Front') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir('Front') {
                    sh 'npm run build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('Front') {
                    sh 'npm run test --watch=false --code-coverage'
                }
            }
        }
        stage('Sonarqube Report') {
            steps {
                dir('Front') {
                    sh 'npm run sonar'
                }
            }
        }
        stage('Package Artifact') {
            steps {
                script {
                    dir('Front') {
                        sh '''
                        mkdir -p /tmp/tarball
                        tar -czf /tmp/tarball/valoparamadminfront.tgz -C dist .
                        mv /tmp/tarball/valoparamadminfront.tgz dist/
                        rm -rf /tmp/tarball
                        '''
                    }
                }
            }
        }
        stage('Deploy to Nexus') {
            steps {
                script {
                    dir('Front') {
                        def packageJson = readJSON file: 'package.json'
                        def packageName = packageJson.name
                        def packageVersion = packageJson.version
                        def username = 'admin'
                        def password = 'nexus'
                        def npmPackagePath = "dist/valoparamadminfront.tgz"

                        sh """
                        curl -u ${username}:${password} --upload-file ${npmPackagePath} http://192.168.33.10:8081/repository/maven-releases/
                        """
                    }
                }
            }
        }
        stage('Docker Build Image') {
            steps {
                dir('Front') {
                    sh 'docker build -t fediijat/valoparamadminfront .'
                }
            }
        }
        stage('Docker Push') {
            steps {
                dir('Front') {
                    sh 'docker push fediijat/valoparamadminfront'
                }
            }
        }
    }
}
