/**
 * OpenApi specification
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto {
    firstname?: string;
    lastname?: string;
    password?: string;
    email?: string;
    company?: string;
    phone?: string;
    role?: RegisterDto.RoleEnum;
    auth?:string;
}
export namespace RegisterDto {
    export type RoleEnum = 'EXPERT' | 'ADMIN' | 'CONSULTANT';
    export const RoleEnum = {
        EXPERT: 'EXPERT' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Consultant: 'CONSULTANT' as RoleEnum
    };
}


