/**
 * OpenApi specification
 * OpenApi documentation for Admin Module Demo
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto {
    id?: number;
    firstname?: string;
    lastname?: string;
    email?: string;
    active?: boolean;
    nonExpired?: boolean;
    profileImagePath?: string;
    phone?: string;
    company?: string;
    role?: UserDto.RoleEnum;
    error?: string;
  authorities?:string[];

}
export namespace UserDto {
    export type RoleEnum = 'EXPERT' | 'ADMIN' | 'CONSULTANT';
    export const RoleEnum = {
        EXPERT: 'EXPERT' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Consultant: 'CONSULTANT' as RoleEnum
    };
}


